# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-03-14 05:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Counter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='-', max_length=1000)),
                ('firstContactTime', models.DateTimeField(auto_now_add=True)),
                ('ordering', models.IntegerField(default=0)),
                ('reply', models.CharField(default='', max_length=2000)),
                ('hidden', models.BooleanField(default=False)),
                ('phone_no', models.CharField(default='-', max_length=20)),
                ('device_id', models.CharField(max_length=1000)),
                ('device_type', models.CharField(default='telegram', max_length=1000)),
                ('context', models.CharField(default='', max_length=1000)),
                ('operator_id', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['ordering'],
            },
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('action', models.CharField(max_length=1000)),
                ('result', models.CharField(max_length=100)),
                ('positive', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now=True)),
                ('message', models.CharField(max_length=10000)),
                ('isReply', models.BooleanField(default=False)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cc.Customer')),
            ],
            options={
                'ordering': ['time'],
            },
        ),
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(default='', max_length=5000)),
                ('reply', models.CharField(default='', max_length=5000)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
