# Generated by Django 2.0.2 on 2018-03-02 07:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChatLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('message', models.CharField(max_length=10000)),
                ('isReply', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['time'],
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='-', max_length=1000)),
                ('firstContactTime', models.DateTimeField(auto_now_add=True)),
                ('ordering', models.IntegerField(default=0)),
                ('hidden', models.BooleanField(default=False)),
                ('phone_no', models.CharField(default='-', max_length=20)),
                ('device_id', models.CharField(max_length=1000)),
                ('device_type', models.CharField(default='telegram', max_length=1000)),
            ],
            options={
                'ordering': ['ordering'],
            },
        ),
        migrations.AddField(
            model_name='chatline',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cc.Customer'),
        ),
    ]
