# Generated by Django 2.0.2 on 2018-03-04 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cc', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='operator_id',
            field=models.IntegerField(default=0),
        ),
    ]
