# Generated by Django 2.0.2 on 2018-03-04 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cc', '0002_customer_operator_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('action', models.CharField(max_length=1000)),
                ('result', models.CharField(max_length=100)),
                ('positive', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.RenameModel(
            old_name='ChatLine',
            new_name='Messages',
        ),
    ]
