# Generated by Django 2.0.2 on 2018-03-04 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cc', '0003_auto_20180304_1215'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Messages',
            new_name='Message',
        ),
    ]
