# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-03-04 10:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cc', '0004_auto_20180304_1454'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='reply',
            field=models.CharField(default='', max_length=2000),
        ),
    ]
