# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-03-04 17:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cc', '0007_counter'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='context',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
