# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-03-11 06:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cc', '0008_customer_context'),
    ]

    operations = [
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(default='', max_length=5000)),
                ('reply', models.CharField(default='', max_length=5000)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
